# api/main.py
"""
Thin transport layer. Validates input, calls data/ (or agent/, once
ready), returns JSON via the Pydantic models in api/models.py.

Hard rule (PROJECT_SPEC.md section 4): no business logic lives here.
Every calculation already happened in data/ — this file only wires HTTP
requests to already-tested functions and shapes the response.

Run locally:
    uv run uvicorn api.main:app --reload --port 8000

Docs (auto-generated by FastAPI): http://localhost:8000/docs
"""

from __future__ import annotations

import os

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from api.models import (
    AgentQueryRequest,
    AgentQueryResponse,
    ComparisonSummary,
    CoolPointCandidate,
    HealthResponse,
    HeatmapPoint,
    ShiftPoint,
    WorkerDetail,
    WorkerStatus,
)
from data.baseline import comparison_summary
from data.cool_points import get_candidates_with_current_temp
from data.fortyguard_client import (
    DEMO_HOURS,
    STUDY_DATE,
    FortyGuardError,
    get_temperature_grid,
)
from data.mock_data import WORKER_ROSTER, generate_mock_shift, generate_mock_workers
from data.real_shift_builder import (
    MissingRealDataError,
    attach_real_temperatures,
    build_real_workers,
)
from data.worker_status import (
    UnknownWorkerError,
    get_worker_status,
    list_workers_at_risk,
)

# STUDY_DATE now imported from data.fortyguard_client — single source
# of truth shared with the pull script, avoiding drift between the two.

app = FastAPI(
    title="HeatDose API",
    description=(
        "Thin transport layer over data/ and agent/. See "
        "docs/data_contract.md for the authoritative shapes."
    ),
    version="1.0.0",
)

# CORS_ORIGINS env var: comma-separated list, e.g.
# "https://heatdose.vercel.app,http://localhost:5173"
# Defaults to "*" for local development only — set a real allow-list
# before judging, per PROJECT_SPEC.md's API-key/security requirements.
_origins = os.environ.get("CORS_ORIGINS", "*")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"] if _origins == "*" else _origins.split(","),
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# --------------------------------------------------------------------
# Health
# --------------------------------------------------------------------


@app.get("/api/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(status="ok")


# --------------------------------------------------------------------
# Workers
# --------------------------------------------------------------------


@app.get("/api/workers", response_model=list[WorkerStatus])
def list_workers() -> list[WorkerStatus]:
    """All workers with status, sorted by excess_dose descending."""
    try:
        # "low" is the lowest band, so this returns everyone.
        statuses = list_workers_at_risk(min_level="low")
    except MissingRealDataError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return [WorkerStatus(**s) for s in statuses]


@app.get("/api/workers/{worker_id}", response_model=WorkerDetail)
def get_worker(worker_id: str) -> WorkerDetail:
    """One worker's status plus their full shift trail, for the map."""
    if worker_id not in WORKER_ROSTER:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown worker_id: {worker_id!r}. "
            f"Known workers: {sorted(WORKER_ROSTER)}",
        )

    try:
        status = get_worker_status(worker_id)

        config = WORKER_ROSTER[worker_id]
        mock_shift = generate_mock_shift(
            worker_id,
            route_profile=config["profile"],
            start_hour=config["start_hour"],
        )
        real_shift = attach_real_temperatures(mock_shift)
    except UnknownWorkerError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except MissingRealDataError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    return WorkerDetail(
        **status,
        shift=[ShiftPoint(**point) for point in real_shift],
    )


# --------------------------------------------------------------------
# Heatmap
# --------------------------------------------------------------------


@app.get("/api/heatmap", response_model=list[HeatmapPoint])
def get_heatmap(hour: int) -> list[HeatmapPoint]:
    """Full-resolution real temperature grid for one hour, for map colouring."""
    if hour not in DEMO_HOURS:
        raise HTTPException(
            status_code=400,
            detail=f"hour must be one of {DEMO_HOURS.start}-{DEMO_HOURS.stop - 1} "
            f"(the only hours cached for the demo — no live calls are ever "
            f"made from this endpoint).",
        )

    try:
        grid = get_temperature_grid(STUDY_DATE, hour, use_cache=True)
    except FortyGuardError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    if not grid:
        raise HTTPException(
            status_code=503,
            detail=f"No cached data for hour {hour}. "
            f"Pull it with: uv run python data/fortyguard_client.py --pull-day",
        )

    return [HeatmapPoint(**point) for point in grid]


# --------------------------------------------------------------------
# Cool points
# --------------------------------------------------------------------


@app.get("/api/cool-points", response_model=list[CoolPointCandidate])
def get_cool_points(hour: int) -> list[CoolPointCandidate]:
    """
    All candidate rest points with current temps for the given hour.

    Note (see data/cool_points.py's module docstring): these
    temperatures are synthetic (mock_data.temp_at()), not real
    FortyGuard data — a deliberate scope decision, not a bug.
    """
    if not 0 <= hour <= 23:
        raise HTTPException(status_code=400, detail="hour must be 0-23")

    candidates = get_candidates_with_current_temp(hour)
    return [CoolPointCandidate(**c) for c in candidates]


# --------------------------------------------------------------------
# Comparison — the pitch endpoint
# --------------------------------------------------------------------


@app.get("/api/comparison", response_model=ComparisonSummary)
def get_comparison() -> ComparisonSummary:
    """
    Hyperlocal continuous tracking vs. single-check-in baseline, per
    worker and roster-wide. See docs/methodology.md's "What we
    measured" section — this compares TIME (continuous vs. one check),
    not location/zone.
    """
    try:
        mock_workers = generate_mock_workers()
        real_workers = build_real_workers(mock_workers)
        summary = comparison_summary(real_workers)
    except MissingRealDataError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    return ComparisonSummary(**summary)


# --------------------------------------------------------------------
# Agent — STUB until agent/ is ready
# --------------------------------------------------------------------


@app.post("/api/agent/query", response_model=AgentQueryResponse)
def agent_query(request: AgentQueryRequest) -> AgentQueryResponse:
    """
    TODO(agent owner): replace this stub with a real call into agent/
    once it exists. Kept as a 200-OK stub (not a 501) deliberately —
    this lets the web owner build and test the chat panel's request/
    response wiring right now, without waiting for the agent to exist.
    Swap the body of this function for a real agent call; the response
    shape (AgentQueryResponse) should not need to change.
    """
    return AgentQueryResponse(
        answer=(
            "Agent not yet wired up. This is a placeholder response so "
            "the web layer can be built against the final response shape "
            f"now. Your question was: {request.question!r}"
        ),
        tool_trace=[],
    )
